"""
OG-Japan calibration table: every calibrated value, with its source.

Prints the full parameter surface the calibration overrides, so the answer to
"where does this number come from?" is one command away rather than a hunt
through module comments. Also states what is deliberately NOT calibrated, since
in a country port the parameters you did not set are as consequential as the
ones you did.

Usage:
    python examples/calibration_table.py            # markdown to stdout
    python examples/calibration_table.py --write    # also write docs/CALIBRATION_TABLE.md
"""

import argparse
import os

import numpy as np

from ogjpn import macro_params, pension_params, tax_params

CUR_PATH = os.path.abspath(os.path.dirname(__file__))
OUT = os.path.join(CUR_PATH, "..", "docs", "CALIBRATION_TABLE.md")


def _fmt(v):
    a = np.asarray(v)
    if a.ndim == 0 or a.size == 1:
        x = float(a.flat[0]) if a.dtype.kind in "fiu" else a.flat[0]
        return f"{x:.6g}" if isinstance(x, float) else str(x)
    if a.size <= 3:
        return "[" + ", ".join(f"{float(x):.6g}" for x in a.ravel()) + "]"
    return f"{a.shape} array, first = {float(a.ravel()[0]):.6g}"


# (parameter, source)  -- the source is the authority, not the derivation;
# the derivation lives in the module comment that sets the value.
SOURCES = {
    "g_y_annual": "PWT via FRED: real GDP / (persons x hours), 2000-2019",
    "delta_annual": "World Bank NY.ADJ.DKAP.GN.ZS, CFC/K, 2016-2019",
    "gamma": "PWT labour share (FRED LABSHPJPA156NRUG), 2015-2023",
    "beta_annual": "calibrated to the PWT capital-output ratio of 3.70",
    "initial_debt_ratio": "OECD Economic Outlook GNFLQ, net, end-2024",
    "debt_ratio_ss": "policy anchor (chosen, not measured)",
    "initial_foreign_debt_ratio": "MOF JGB/T-Bill holders, Mar 2026",
    "zeta_D": "set equal to the stock share (family default)",
    "zeta_K": "not anchored; Japan inward FDI ~5% of GDP",
    "r_gov_scale": "reduced pass-through: BOJ holds 42.2% of JGBs",
    "r_gov_shift": "OECD EO net interest / net debt, 2015-2024",
    "alpha_G": "World Bank NE.CON.GOVT.ZS, general government, 2024",
    "alpha_T": "IPSS social security spending, CASH only (in-kind is in G)",
    "alpha_I": "Japan public gross fixed capital formation",
    "TPI_outer_method": "family run-engineering guidance",
    "tau_payroll": "OECD RevStats 2025 SSC 13.18% / labour share 0.57",
    "frac_tax_payroll": "OECD RevStats 2025: SSC / (SSC + PIT)",
    "tau_c": "tuned to OECD RevStats goods+services 6.82% of GDP",
    "cit_rate": "Japan statutory combined national + local",
    "adjustment_factor_for_cit_receipts": "tuned to CIT 4.70% of GDP",
    "p_wealth": "tuned to property taxes 2.21% of GDP",
    "h_wealth": "flat-rate wealth tax form",
    "m_wealth": "small positive: m=0 divides 0/0 at zero wealth",
    "tau_bq": "tuned to inheritance tax 0.55% of GDP",
    "tax_func_type": "Gouveia-Strauss: floors the effective rate at zero",
    "etr_params": "phi0 = statutory top 55%; phi2 tuned to PIT 6.17% of GDP",
    "mtrx_params": "same triple (analytically consistent)",
    "mtry_params": "same triple (analytically consistent)",
    "pension_system": "Japan's public pension is earnings-related DB",
    "alpha_db": "OECD PaG 32.4% x survivors/disability uplift, then fitted",
    "yr_contrib": "full Basic Pension contribution period",
    "avg_earn_num_years": "Japan averages the ENTIRE career, not final salary",
    "retirement_age": "pensionable age, both tiers",
    "mean_income_data": "National Tax Agency private-sector wages, 2023",
}

NOT_CALIBRATED = [
    ("chi_n", "OG-USA's profile", "labour input per working-age person is "
     "within 1% of the US (1,278 vs 1,288 hours), so borrowing is harmless"),
    ("lambdas", "family-standard percentiles", "byte-identical across every "
     "country port; only the earnings tilt differs"),
    ("sigma, frisch", "OG-Core literature values", "deep preference "
     "parameters; no Japanese observable identifies them"),
    ("fert/mort/infmort_gradient", "left unset", "Demographic-Gradients "
     "excludes high-income countries and forbids extrapolating its fallback"),
    ("initial_wealth_ratio", "undiagnosed", "affects the TRANSITION only; "
     "flagged as the main open risk"),
    ("epsilon", "1.0 (Cobb-Douglas)", "no Japanese estimate applied"),
]


def build():
    blocks = [
        ("Macro and open economy", macro_params.get_macro_params()),
        ("Taxes", tax_params.get_tax_params()),
        ("Pensions", pension_params.get_pension_params()),
    ]
    lines = [
        "# OG-Japan calibration table",
        "",
        "Every parameter the calibration overrides, with the authority behind "
        "it. Derivations live in the module comment that sets each value; this "
        "is the index.",
        "",
        "Generated by `examples/calibration_table.py` -- regenerate rather than "
        "edit, so it cannot drift from the shipped values.",
        "",
    ]
    total = 0
    for name, params in blocks:
        lines += [f"## {name}", "", "| Parameter | Value | Source |",
                  "|---|---|---|"]
        for k in sorted(params):
            total += 1
            lines.append(
                f"| `{k}` | `{_fmt(params[k])}` | {SOURCES.get(k, '—')} |"
            )
        lines.append("")

    lines += [
        "## Demographics", "",
        "Pulled live from the UN World Population Prospects via "
        "`ogcore.demographics`, country code 392, with `income_percentiles` "
        "passed so the arrays are J-wide. Fertility, mortality and population "
        "are UN series; immigration is solved as the residual that reconciles "
        "consecutive UN distributions.", "",
        "## Earnings", "",
        "The `e` matrix is built in `ogjpn/income.py` by the family's two-part "
        "method: an NTA age-shape adjustment (Japan 2004 against the US 2003) "
        "followed by a single-scalar tilt to Japan's Gini of 32.3.", "",
        "## Deliberately NOT calibrated", "",
        "In a country port the parameters you did not set matter as much as "
        "those you did, because anything unset silently keeps OG-Core's United "
        "States value. These are left, with reasons:", "",
        "| Parameter | State | Why |", "|---|---|---|",
    ]
    for k, state, why in NOT_CALIBRATED:
        lines.append(f"| `{k}` | {state} | {why} |")
    lines += ["", f"**{total} parameters calibrated.**", ""]
    return "\n".join(lines)


def main(write=False):
    text = build()
    print(text)
    if write:
        with open(os.path.abspath(OUT), "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"\n[written to {os.path.relpath(os.path.abspath(OUT))}]")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    main(**vars(ap.parse_args()))
